### ISSUE TITLE
Static file handlers of example servers break w/ recent CherryPy (return unicode instead of bytes)

### ISSUE THREAD

**Issue by jgehrcke** [rohe/pyoidc#232]
The WSGI applications in the examples erroneously return text/unicode objects in the static file handlers. CherryPy (the WSGI server used for the examples in this repo) has recently checked in a change that rightfully forces WSGI apps to send _just_ bytes, and nothing else:

https://github.com/cherrypy/cherrypy/commit/6251b05ddf273ecfdd8bf49327f728671917a4f2

That's how the pyoidc examples can now fail from a user agent's point of view:
```
Remote key update from 'https://127.0.0.1:8092/static/jwks.json' failed, HTTP status 500
```

That's the corresponding traceback on OP side:
```
ValueError('WSGI Applications must yield bytes',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 2337, in respond
    raise ValueError('WSGI Applications must yield bytes')
ValueError: WSGI Applications must yield bytes
```

**Comment by jgehrcke** [comment]
The patch was merged, so closing this issue.
