### ISSUE TITLE
Sphinx build reveals missing import of `JWT`?

### ISSUE THREAD

**Issue by lwm** [rohe/pyoidc#257]
```
sphinx-build -b html doc/ doc/_build/html -W
Running Sphinx v1.5.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 17 source files that are out of date
updating environment: 17 added, 0 changed, 0 removed
reading sources... [100%] index/oic.utils.userinfo                                                                                                                        

Warning, treated as error:
/home/lwm/wages/fsfe/oidc-stuff/pyoidc/doc/index/oic.extension.rst:34: WARNING: autodoc: failed to import module 'oic.extension.heart'; the following exception was raised:
Traceback (most recent call last):
  File "/home/lwm/wages/fsfe/oidc-stuff/pyoidc/.venv/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
    __import__(self.modname)
  File "/home/lwm/wages/fsfe/oidc-stuff/pyoidc/src/oic/extension/heart.py", line 12, in <module>
    class PrivateKeyJWT(JWT):
NameError: name 'JWT' is not defined
```

**Comment by rohe** [comment]
Ah, interesting! Sphinx brings a new set of tools for keeping the software in check :-/

**Comment by lwm** [comment]
:)

**Comment by lwm** [comment]
Although, strangely, this hasn't been revealed in the Travis build. Can you reproduce it?

**Comment by rohe** [comment]
There are no tests for this modul so no, nothing was discovered by Travis.

**Comment by lwm** [comment]
Travis [does build the documentation though!](https://github.com/rohe/pyoidc/blob/master/.travis.yml#L43). Assuming this is closed by https://github.com/rohe/pyoidc/commit/8e5c445cc82d6ee80107fd8145873e27e55d977f. Thanks!
