### ISSUE TITLE
OP2 Add saml2 to your dependencies 

### ISSUE THREAD

**Issue by H0neyBadger** [rohe/pyoidc#33]
On op2 I get the error :

Traceback (most recent call last):
  File "server.py", line 20, in <module>
    from oic.utils.userinfo.aa_info import AaUserInfo
  File ".../oic-0.5.0beta-py2.6.egg/oic/utils/userinfo/aa_info.py", line 4, in <module>
    from saml2 import saml, samlp

**Comment by rohe** [comment]
Using SAML for getting user info is a corner case so I don't want to bring that dependency into
setup.py. Should instead be in a op2/README file. To be written.
